### ISSUE TITLE
Build errors on Debian Jessie (testing)

### ISSUE THREAD

**Issue by svaksha** [JuliaWeb/MbedTLS.jl#34] opened 2016-03-21 12:57 UTC
On Debian Jessie (testing), running Version 0.4.3 (2016-01-12 21:37 UTC) x86_64-linux-gnu, trying to build MbedTLS results in these errors:

```
$ Pkg.build("MbedTLS")
INFO: Building MbedTLS
INFO: Attempting to Create directory /home/i/.julia/v0.4/MbedTLS/deps/downloads
INFO: Directory /home/i/.julia/v0.4/MbedTLS/deps/downloads already created
INFO: Downloading file https://cache.julialang.org/https://tls.mbed.org/download/mbedtls-2.1.1-apache.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
===============================[ ERROR: MbedTLS ]===============================

LoadError: failed process: Process(`curl -f -o /home/i/.julia/v0.4/MbedTLS/deps/downloads/mbedtls-2.1.1-apache.tgz -L https://cache.julialang.org/https://tls.mbed.org/download/mbedtls-2.1.1-apache.tgz`, ProcessExited(77)) [77]
while loading /home/i/.julia/v0.4/MbedTLS/deps/build.jl, in expression starting on line 69

================================================================================

===============================================[ BUILD ERRORS ]================================================

WARNING: MbedTLS had build errors.

 - packages with build errors remain installed in /home/i/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("MbedTLS")`
 - build a single package by running its `deps/build.jl` script

===============================================================================================================
```

Thereafter, building the single package also throws errors:

```
ERROR: LoadError: could not spawn `./cmake_check.sh`: no such file or directory (ENOENT)
 in _jl_spawn at ./process.jl:262
while loading /home/i/.julia/v0.4/MbedTLS/deps/build.jl, in expression starting on line 69
```

Thanks!

**Comment by malmaud** [comment] 2016-04-18 20:30
It seems like this error was just caused by the MbedTLS source files being temporarily unable to download. Let me know if it's still a problem.

**Comment by svaksha** [comment] 2016-04-18 21:21
Julia ver-0.4 on Opensuse
Trying to build it again threw these errors:
```
julia> Pkg.build("MbedTLS")
INFO: Building MbedTLS
WARNING: Could not check MbedTLS version
WARNING: Could not check MbedTLS version
cmake command not found. installing cmake is required for building from source.
===============================[ ERROR: MbedTLS ]===============================

LoadError: failed process: Process(`./cmake_check.sh`, ProcessExited(1)) [1]
while loading /home/m/.julia/v0.4/MbedTLS/deps/build.jl, in expression starting on line 69

================================================================================

======================================================================[ BUILD ERRORS ]=======================================================================

WARNING: MbedTLS had build errors.

 - packages with build errors remain installed in /home/m/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("MbedTLS")`
 - build a single package by running its `deps/build.jl` script

=============================================================================================================================================================
```

Then, tried to build the script as suggested which also threw this error: 

```
WARNING: Could not check MbedTLS version
WARNING: Could not check MbedTLS version
ERROR: LoadError: could not spawn `./cmake_check.sh`: no such file or directory (ENOENT)
 in _jl_spawn at process.jl:262
 in anonymous at process.jl:415
 in run at /home/m/.julia/v0.4/BinDeps/src/BinDeps.jl:479
 in satisfy! at /home/m/.julia/v0.4/BinDeps/src/dependencies.jl:798
 in satisfy! at /home/m/.julia/v0.4/BinDeps/src/dependencies.jl:776
 in anonymous at /home/m/.julia/v0.4/BinDeps/src/dependencies.jl:831
while loading /home/m/.julia/v0.4/MbedTLS/deps/build.jl, in expression starting on line 69

```

**Comment by malmaud** [comment] 2016-04-18 21:22
Like the error says, you have to have 'cmake' installed to build mbedtls
from source.

**Comment by svaksha** [comment] 2016-04-19 09:31
@malmaud the debian jessie (testing) machine already has cmake :
```
cmake is already the newest version (3.5.1-1).
```
I still get Build errors on the julia ver-0.4.6-pre+18, commit 198644a* (18 days old release-0.4), 64-bit.

**Comment by malmaud** [comment] 2016-05-10 15:03
Are you still getting an error on opensuse 42.1? That warning about checking the MbedTLS version isn't necessarily a problem.

**Comment by svaksha** [comment] 2016-05-11 10:34
@malmaud, on openSUSE, the REPL error has changed to,
```
julia> Pkg.build("MbedTLS")
INFO: Building MbedTLS
WARNING: Could not check MbedTLS version
WARNING: Could not check MbedTLS version
```
Then, I tried to build it for ver0.4, but it threw the same error as above.

**Comment by malmaud** [comment] 2016-05-11 11:43
I'm still a little confused - what exactly is the error? Those warnings aren't necessarily errors.

**Comment by Sisyphuss** [comment] 2016-05-14 12:01
I have the same error on Ubuntu 14.04:

```
LoadError: failed process: Process(`curl -f -o /home/###/.julia/v0.4/MbedTLS/deps/downloads/mbedtls-2.1.1-apache.tgz -L https://cache.julialang.org/https://tls.mbed.org/download/mbedtls-2.1.1-apache.tgz`, ProcessExited(77)) [77]
while loading /home/###/.julia/v0.4/MbedTLS/deps/build.jl, in expression starting on line 69
```

**Comment by lmmx** [comment] 2016-06-23 18:42
@Sisyphuss  I had the same error on Linux Mint 17 (Qiana, Ubuntu 14.04 base) 

```
julia> Pkg.build("MbedTLS")
INFO: Building MbedTLS
INFO: Attempting to Create directory /home/louis/.julia/v0.4/MbedTLS/deps/downloads
INFO: Directory /home/louis/.julia/v0.4/MbedTLS/deps/downloads already created
INFO: Downloading file https://cache.julialang.org/https://tls.mbed.org/download/mbedtls-2.1.1-apache.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
===============================[ ERROR: MbedTLS ]===============================

LoadError: failed process: Process(`curl -f -o /home/louis/.julia/v0.4/MbedTLS/deps/downloads/mbedtls-2.1.1-apache.tgz -L https://cache.julialang.org/https://tls.mbed.org/download/mbedtls-2.1.1-apache.tgz`, ProcessExited(77)) [77]
while loading /home/louis/.julia/v0.4/MbedTLS/deps/build.jl, in expression starting on line 69

================================================================================

=======================================================================================[ BUILD ERRORS ]=======================================================================================

WARNING: MbedTLS had build errors.

 - packages with build errors remain installed in /home/louis/.julia/v0.4
 - build the package(s) and all dependencies with `Pkg.build("MbedTLS")`
 - build a single package by running its `deps/build.jl` script

==============================================================================================================================================================================================
```

The `-f` flag in the call to `curl` silences failures, so I just manually `wget`-downloaded the file and moved it to the location specified in the curl command, then `Pkg.build` ran fine - it detects if the file is already there. (Then I ran `Pkg.update()`)

**Comment by quinnj** [comment] 2016-12-01 04:42
Should be fixed on master now that we use the julia-shipped mbed shared libraries

**Closed by quinnj** 2016-12-01 04:42 UTC
Labels: more-information-needed

**Comment by prassee** [comment] 2017-08-03 08:37
Iam still getting this error on SolusOS with Julia 0.6.0
